import AppKit

/// Pasteboard types Myink understands, and the limits it applies when storing pasteboard data.
public enum TypeCatalog {
    public static let fileURL = "public.file-url"
    public static let url = "public.url"
    public static let urlName = "public.url-name"
    public static let plainText = "public.utf8-plain-text"
    public static let utf16Text = "public.utf16-external-plain-text"
    public static let rtf = "public.rtf"
    public static let rtfd = "com.apple.flat-rtfd"
    public static let html = "public.html"
    public static let webArchive = "com.apple.webarchive"
    public static let pdf = "com.adobe.pdf"
    public static let png = "public.png"
    public static let jpeg = "public.jpeg"
    public static let heic = "public.heic"
    public static let gif = "com.compuserve.gif"
    public static let webp = "org.webmproject.webp"
    public static let tiff = "public.tiff"
    public static let webURLsWithTitles = "WebURLsWithTitlesPboardType"
    public static let legacyURL = "Apple URL pasteboard type"
    public static let legacyFilenames = "NSFilenamesPboardType"

    /// Compressed image formats, preferred over TIFF (which apps often add as a lossless extra).
    public static let compressedImageTypes = [png, jpeg, heic, gif, webp]
    public static let richTextTypes = [rtfd, rtf]
    public static let textTypes = [rtfd, rtf, html, webArchive, plainText, utf16Text]

    public static var promiseTypes: [String] {
        NSFilePromiseReceiver.readableDraggedTypes
    }

    /// Types the shelf registers for as a drag destination.
    public static var acceptedDragTypes: [String] {
        [fileURL, legacyFilenames, url, legacyURL, webURLsWithTitles, pdf, tiff] + compressedImageTypes + textTypes + promiseTypes
    }

    /// Whether a drag carrying `types` offers anything Myink can hold.
    public static func acceptsDrag(types: [String]) -> Bool {
        let accepted = Set(acceptedDragTypes)
        return types.contains { accepted.contains($0) }
    }

    /// Captured for classification (file URLs, link titles) even though they're never replayed.
    public static let classificationTypes: Set<String> = [fileURL, url, urlName, webURLsWithTitles]

    /// Per-representation and per-item limits for stored pasteboard data.
    public static let maxRepresentationBytes = 32 * 1024 * 1024
    public static let maxItemBytes = 64 * 1024 * 1024

    /// Types never stored in snippets: file references, promise plumbing and app-internal types.
    static let excludedFromSnippets: Set<String> = [
        fileURL, "com.apple.finder.node", "com.apple.pasteboard.promised-file-url",
        "com.apple.pasteboard.promised-file-content-type", "com.apple.pasteboard.promised-file-name",
        "com.apple.pasteboard.promised-suggested-file-name", "com.apple.NSFilePromiseItemMetaData",
        "com.apple.pasteboard.NSFilePromiseID", "com.apple.pasteboard.promised-file-url-string"
    ]

    /// Modern UTI-style types worth storing. Legacy names ("NeXT … pasteboard type", "Apple URL
    /// pasteboard type"), dynamic `dyn.*` types and Carbon flavors are regenerated by AppKit on demand.
    public static func isStorable(_ type: String) -> Bool {
        guard type.contains("."), !type.contains(" "), !type.hasPrefix("dyn."),
              !type.hasPrefix("CorePasteboardFlavorType") else { return false }
        return !excludedFromSnippets.contains(type) && !promiseTypes.contains(type)
    }
}
